Repository PennLINC/qsirecon, pull requests merged in 2024-08, with the labels that each got.

#8 Remove internal version of LiterateWorkflow
  qsirecon/engine/__init__.py
  qsirecon/engine/workflows.py
  qsirecon/workflows/anatomical/surface.py
  qsirecon/workflows/anatomical/volume.py
  qsirecon/workflows/base.py
  qsirecon/workflows/dwi/base.py
  qsirecon/workflows/dwi/confounds.py
  qsirecon/workflows/dwi/derivatives.py
  qsirecon/workflows/dwi/distortion_group_merge.py
  qsirecon/workflows/dwi/finalize.py
  qsirecon/workflows/dwi/fsl.py
  qsirecon/workflows/dwi/hmc.py
  qsirecon/workflows/dwi/hmc_sdc.py
  qsirecon/workflows/dwi/intramodal_template.py
  qsirecon/workflows/dwi/merge.py
  qsirecon/workflows/dwi/pre_hmc.py
  qsirecon/workflows/dwi/qc.py
  qsirecon/workflows/dwi/registration.py
  qsirecon/workflows/dwi/resampling.py
  qsirecon/workflows/dwi/util.py
  qsirecon/workflows/fieldmap/base.py
  qsirecon/workflows/fieldmap/drbuddi.py
  qsirecon/workflows/fieldmap/pepolar.py
  qsirecon/workflows/fieldmap/syn.py
  qsirecon/workflows/recon/amico.py
  qsirecon/workflows/recon/anatomical.py
  qsirecon/workflows/recon/build_workflow.py
  qsirecon/workflows/recon/converters.py
  qsirecon/workflows/recon/dipy.py
  qsirecon/workflows/recon/dsi_studio.py
  qsirecon/workflows/recon/mrtrix.py
  qsirecon/workflows/recon/scalar_mapping.py
  qsirecon/workflows/recon/steinhardt.py
  qsirecon/workflows/recon/tortoise.py
  qsirecon/workflows/reports.py
Labels: refactor

#40 Drop and modify infrastructure files
  .zenodo.json
  CHANGES.rst
  CONTRIBUTING.md
  LICENSE
  MANIFEST.in
  README.rst
  REFERENCES.md
  long_description.rst
  pyproject.toml
  update_changes.sh
Labels: maintenance

#41 Update docs and trigger RTD build
  docs/installation.rst
Labels: ignore-for-release

#5 Remove QSIPrep-specific tests
  .circleci/config.yml
  Dockerfile
  pyproject.toml
  qsirecon/cli/run.py
  qsirecon/tests/test_cli.py
  qsirecon/tests/utils.py
  qsirecon/workflows/recon/__init__.py
Labels: testing

#7 Write out QSIRecon pipeline-wise reports
  docs/api.rst
  pyproject.toml
  qsirecon/cli/parser.py
  qsirecon/cli/run.py
  qsirecon/cli/workflow.py
  qsirecon/config.py
  qsirecon/data/__init__.py
  qsirecon/data/reports-spec-anat.yml
  qsirecon/data/reports-spec-dwi.yml
  qsirecon/data/reports-spec.yml
  qsirecon/reports/core.py
  qsirecon/tests/data/amico_noddi_outputs.txt
  qsirecon/tests/data/autotrack_outputs.txt
  qsirecon/tests/data/cuda_outputs.txt
  qsirecon/tests/data/dipy_dki_outputs.txt
  qsirecon/tests/data/dipy_mapmri_outputs.txt
  qsirecon/tests/data/mrtrix3_recon_outputs.txt
  qsirecon/tests/data/mrtrix_singleshell_ss3t_act_outputs.txt
  qsirecon/tests/data/mrtrix_singleshell_ss3t_noact_outputs.txt
  qsirecon/tests/data/pyafq_recon_external_trk_outputs.txt
  qsirecon/tests/data/pyafq_recon_full_outputs.txt
  qsirecon/tests/data/scalar_mapper_outputs.txt
  qsirecon/tests/data/tortoise_recon_outputs.txt
  qsirecon/tests/test_cli.py
  qsirecon/viz/__init__.py
  qsirecon/viz/report.tpl
  qsirecon/viz/reports.py
  qsirecon/workflows/base.py
  qsirecon/workflows/recon/anatomical.py
  qsirecon/workflows/recon/build_workflow.py
  qsirecon/workflows/recon/mrtrix.py
  qsirecon/workflows/reports.py
  tests/test_lesion.py
Labels: bug

#55 Add ng, perng, parng, and mapcoeffs to Dipy MAPMRI outputs
  qsirecon/interfaces/dipy.py
  qsirecon/interfaces/recon_scalars.py
  qsirecon/tests/data/dipy_mapmri_outputs.txt
  qsirecon/tests/test_cli.py
  qsirecon/workflows/recon/dipy.py
Labels: enhancement

#53 Write out reports to individual reconstruction derivative folders
  qsirecon/data/bids.json
  qsirecon/data/io_spec.json
  qsirecon/interfaces/bids.py
  qsirecon/interfaces/recon_scalars.py
  qsirecon/interfaces/reports.py
  qsirecon/tests/data/amico_noddi_outputs.txt
  qsirecon/tests/data/autotrack_outputs.txt
  qsirecon/tests/data/dipy_dki_outputs.txt
  qsirecon/tests/data/dipy_mapmri_outputs.txt
  qsirecon/tests/data/mrtrix3_recon_outputs.txt
  qsirecon/tests/data/mrtrix_singleshell_ss3t_act_outputs.txt
  qsirecon/tests/data/mrtrix_singleshell_ss3t_noact_outputs.txt
  qsirecon/tests/data/pyafq_recon_external_trk_optional_outputs.txt
  qsirecon/tests/data/pyafq_recon_external_trk_outputs.txt
  qsirecon/tests/data/pyafq_recon_full_optional_outputs.txt
  qsirecon/tests/data/pyafq_recon_full_outputs.txt
  qsirecon/tests/data/scalar_mapper_outputs.txt
  qsirecon/tests/data/tortoise_recon_outputs.txt
  qsirecon/utils/bids.py
  qsirecon/workflows/base.py
  qsirecon/workflows/recon/amico.py
  qsirecon/workflows/recon/anatomical.py
  qsirecon/workflows/recon/converters.py
  qsirecon/workflows/recon/dipy.py
  qsirecon/workflows/recon/dsi_studio.py
  qsirecon/workflows/recon/mrtrix.py
  qsirecon/workflows/recon/pyafq.py
  qsirecon/workflows/recon/scalar_mapping.py
  qsirecon/workflows/recon/steinhardt.py
  qsirecon/workflows/recon/tortoise.py
Labels: bug

#56 [DOCS] Reorganize documentation
  README.rst
  docs/_static/EPIT1Normalization.svg
  docs/_static/T1MNINormalization.svg
  docs/_static/brainextraction_t1.svg
  docs/_static/qsiprep_workflow.svg
  docs/_static/sampling_scheme.gif
  docs/_static/segmentation.svg
  docs/_static/sub-abcd_carpetplot.svg
  docs/_static/sub-pnc_carpetplot.png
  docs/_static/unwarping.svg
  docs/anat/base.rst
  docs/api.rst
  docs/building_workflows.rst
  docs/builtin_workflows.rst
  docs/changes.rst
  docs/citing.rst
  docs/comparisons.md
  docs/connectivity_matrices.rst
  docs/getting_started.rst
  docs/help.rst
  docs/index.rst
  docs/input_data.rst
  docs/installation.rst
  docs/license.rst
  docs/links.rst
  docs/quickstart.rst
  docs/reconstruction copy.rst
  docs/reconstruction.rst
  docs/usage.rst
  qsirecon/cli/parser.py
  qsirecon/utils/bids.py
  qsirecon/workflows/base.py
  qsirecon/workflows/recon/__init__.py
  qsirecon/workflows/recon/anatomical.py
  qsirecon/workflows/recon/dipy.py
  qsirecon/workflows/recon/dsi_studio.py
  qsirecon/workflows/recon/mrtrix.py
  qsirecon/workflows/recon/scalar_mapping.py
  qsirecon/workflows/recon/steinhardt.py
  qsirecon/workflows/recon/tortoise.py
  qsirecon/workflows/reports.py
Labels: documentation

#64 Bump qsirecon_build image version
  .circleci/config.yml
  Dockerfile
Labels: maintenance, ignore-for-release

#61 Add summary reportlets to HTML report
  pyproject.toml
  qsirecon/cli/run.py
  qsirecon/config.py
  qsirecon/data/io_spec.json
  qsirecon/interfaces/reports.py
  qsirecon/interfaces/utils.py
  qsirecon/workflows/base.py
Labels: bug

#66 Restructure outputs into BIDS datasets
  qsirecon/cli/run.py
  qsirecon/interfaces/bids.py
  qsirecon/tests/data/amico_noddi_outputs.txt
  qsirecon/tests/data/autotrack_outputs.txt
  qsirecon/tests/data/dipy_dki_outputs.txt
  qsirecon/tests/data/dipy_mapmri_outputs.txt
  qsirecon/tests/data/mrtrix3_recon_outputs.txt
  qsirecon/tests/data/mrtrix_singleshell_ss3t_act_outputs.txt
  qsirecon/tests/data/mrtrix_singleshell_ss3t_noact_outputs.txt
  qsirecon/tests/data/pyafq_recon_external_trk_optional_outputs.txt
  qsirecon/tests/data/pyafq_recon_external_trk_outputs.txt
  qsirecon/tests/data/pyafq_recon_full_optional_outputs.txt
  qsirecon/tests/data/pyafq_recon_full_outputs.txt
  qsirecon/tests/data/scalar_mapper_outputs.txt
  qsirecon/tests/data/tortoise_recon_outputs.txt
  qsirecon/utils/bids.py
  qsirecon/workflows/base.py
  qsirecon/workflows/recon/anatomical.py
Labels: breaking-change

#76 Fix QSIRecon Entrypoint
  Dockerfile
  qsirecon/tests/data/pyafq_recon_external_trk_optional_outputs.txt
  qsirecon/tests/data/pyafq_recon_external_trk_outputs.txt
  qsirecon/tests/data/pyafq_recon_full_optional_outputs.txt
  qsirecon/tests/data/pyafq_recon_full_outputs.txt
Labels: bug

#72 Combine `mfp` and `mdp` entities into single `param` entity
  qsirecon/data/io_spec.json
  qsirecon/interfaces/bids.py
  qsirecon/interfaces/recon_scalars.py
  qsirecon/tests/data/amico_noddi_outputs.txt
  qsirecon/tests/data/dipy_dki_outputs.txt
  qsirecon/tests/data/dipy_mapmri_outputs.txt
  qsirecon/tests/data/mrtrix3_recon_outputs.txt
  qsirecon/tests/data/mrtrix_singleshell_ss3t_act_outputs.txt
  qsirecon/tests/data/mrtrix_singleshell_ss3t_noact_outputs.txt
  qsirecon/tests/data/pyafq_recon_external_trk_outputs.txt
  qsirecon/tests/data/scalar_mapper_outputs.txt
  qsirecon/tests/data/tortoise_recon_outputs.txt
  qsirecon/workflows/recon/amico.py
  qsirecon/workflows/recon/mrtrix.py
  qsirecon/workflows/recon/steinhardt.py
Labels: breaking-change

#79 Move scalar file configs to YAMLs and use a recon scalar workflow
  qsirecon/data/scalars/amico_noddi.yaml
  qsirecon/data/scalars/brainsuite_3dshore.yaml
  qsirecon/data/scalars/dipy_dki.yaml
  qsirecon/data/scalars/dipy_mapmri.yaml
  qsirecon/data/scalars/dsistudio_gqi.yaml
  qsirecon/data/scalars/tortoise.yaml
  qsirecon/interfaces/recon_scalars.py
  qsirecon/interfaces/scalar_mapping.py
  qsirecon/tests/data/amico_noddi_outputs.txt
  qsirecon/tests/data/dipy_dki_outputs.txt
  qsirecon/tests/data/dipy_mapmri_outputs.txt
  qsirecon/tests/data/pyafq_recon_external_trk_optional_outputs.txt
  qsirecon/tests/data/pyafq_recon_full_optional_outputs.txt
  qsirecon/tests/data/scalar_mapper_outputs.txt
  qsirecon/tests/data/tortoise_recon_outputs.txt
  qsirecon/utils/bids.py
  qsirecon/utils/misc.py
  qsirecon/workflows/base.py
  qsirecon/workflows/recon/amico.py
  qsirecon/workflows/recon/build_workflow.py
  qsirecon/workflows/recon/dipy.py
  qsirecon/workflows/recon/dsi_studio.py
  qsirecon/workflows/recon/scalar_mapping.py
  qsirecon/workflows/recon/tortoise.py
  qsirecon/workflows/recon/utils.py
Labels: refactor

#68 Replace `--recon-input-pipeline` with `--input-type`
  .circleci/IngressReconTests.sh
  docs/input_data.rst
  qsirecon/cli/parser.py
  qsirecon/config.py
  qsirecon/workflows/base.py
  qsirecon/workflows/recon/anatomical.py
Labels: breaking-change

#77 Add DatasetLinks to dataset_description.json
  pyproject.toml
  qsirecon/cli/run.py
  qsirecon/config.py
  qsirecon/utils/bids.py
Labels: enhancement

#88 Remove unused `--longitudinal` argument
  qsirecon/cli/parser.py
  qsirecon/config.py
  tests/get_data.py
Labels: breaking-change

#91 Use file lock to avoid concurrent edits to dataset_description.json
  pyproject.toml
  qsirecon/utils/bids.py
Labels: bug

#90 Make all params and models lower-case
  qsirecon/data/scalars/brainsuite_3dshore.yaml
  qsirecon/data/scalars/dipy_dki.yaml
  qsirecon/data/scalars/dipy_mapmri.yaml
  qsirecon/data/scalars/dsistudio_gqi.yaml
  qsirecon/data/scalars/tortoise.yaml
  qsirecon/tests/data/amico_noddi_outputs.txt
  qsirecon/tests/data/autotrack_outputs.txt
  qsirecon/tests/data/dipy_dki_outputs.txt
  qsirecon/tests/data/dipy_mapmri_outputs.txt
  qsirecon/tests/data/mrtrix3_recon_outputs.txt
  qsirecon/tests/data/mrtrix_singleshell_ss3t_act_outputs.txt
  qsirecon/tests/data/mrtrix_singleshell_ss3t_noact_outputs.txt
  qsirecon/tests/data/pyafq_recon_external_trk_optional_outputs.txt
  qsirecon/tests/data/pyafq_recon_external_trk_outputs.txt
  qsirecon/tests/data/scalar_mapper_outputs.txt
  qsirecon/tests/data/tortoise_recon_outputs.txt
  qsirecon/utils/misc.py
  qsirecon/workflows/recon/amico.py
  qsirecon/workflows/recon/dsi_studio.py
  qsirecon/workflows/recon/mrtrix.py
Labels: breaking-change

#93 Compress the tck files
  qsirecon/tests/data/mrtrix3_recon_outputs.txt
  qsirecon/tests/data/mrtrix_singleshell_ss3t_act_outputs.txt
  qsirecon/tests/data/mrtrix_singleshell_ss3t_noact_outputs.txt
  qsirecon/tests/data/pyafq_recon_external_trk_outputs.txt
  qsirecon/workflows/recon/mrtrix.py
Labels: bug

#84 Convert pipeline configs from JSON to YAML
  docs/building_workflows.rst
  docs/input_data.rst
  docs/update_scalardefs.py
  qsirecon/data/pipelines/TORTOISE.json
  qsirecon/data/pipelines/TORTOISE.yaml
  qsirecon/data/pipelines/amico_noddi.json
  qsirecon/data/pipelines/amico_noddi.yaml
  qsirecon/data/pipelines/csdsi_3dshore.json
  qsirecon/data/pipelines/csdsi_3dshore.yaml
  qsirecon/data/pipelines/dipy_3dshore.json
  qsirecon/data/pipelines/dipy_3dshore.yaml
  qsirecon/data/pipelines/dipy_dki.json
  qsirecon/data/pipelines/dipy_dki.yaml
  qsirecon/data/pipelines/dipy_mapmri.json
  qsirecon/data/pipelines/dipy_mapmri.yaml
  qsirecon/data/pipelines/dsi_studio_autotrack.json
  qsirecon/data/pipelines/dsi_studio_autotrack.yaml
  qsirecon/data/pipelines/dsi_studio_gqi.json
  qsirecon/data/pipelines/dsi_studio_gqi.yaml
  qsirecon/data/pipelines/hbcd_scalar_maps.json
  qsirecon/data/pipelines/hbcd_scalar_maps.yaml
  qsirecon/data/pipelines/mrtrix_multishell_msmt_ACT-fast.json
  qsirecon/data/pipelines/mrtrix_multishell_msmt_ACT-fast.yaml
  qsirecon/data/pipelines/mrtrix_multishell_msmt_ACT-hsvs.json
  qsirecon/data/pipelines/mrtrix_multishell_msmt_ACT-hsvs.yaml
  qsirecon/data/pipelines/mrtrix_multishell_msmt_noACT.json
  qsirecon/data/pipelines/mrtrix_multishell_msmt_noACT.yaml
  qsirecon/data/pipelines/mrtrix_multishell_msmt_pyafq_tractometry.json
  qsirecon/data/pipelines/mrtrix_multishell_msmt_pyafq_tractometry.yaml
  qsirecon/data/pipelines/mrtrix_singleshell_ss3t_ACT-fast.json
  qsirecon/data/pipelines/mrtrix_singleshell_ss3t_ACT-fast.yaml
  qsirecon/data/pipelines/mrtrix_singleshell_ss3t_ACT-hsvs.json
  qsirecon/data/pipelines/mrtrix_singleshell_ss3t_ACT-hsvs.yaml
  qsirecon/data/pipelines/mrtrix_singleshell_ss3t_noACT.json
  qsirecon/data/pipelines/mrtrix_singleshell_ss3t_noACT.yaml
  qsirecon/data/pipelines/multishell_scalarfest.json
  qsirecon/data/pipelines/multishell_scalarfest.yaml
  qsirecon/data/pipelines/pyafq_tractometry.json
  qsirecon/data/pipelines/pyafq_tractometry.yaml
  qsirecon/data/pipelines/reorient_fslstd.json
  qsirecon/data/pipelines/reorient_fslstd.yaml
  qsirecon/data/pipelines/ss3t_autotrack.json
  qsirecon/data/pipelines/ss3t_autotrack.yaml
  qsirecon/data/pipelines/test_scalar_maps.json
  qsirecon/data/pipelines/test_scalar_maps.yaml
  qsirecon/workflows/base.py
Labels: refactor
