Repository PennLINC/qsirecon, pull requests merged in 2024-11, with the labels that each got.

#126 Fix infant anatomical ingression
  qsirecon/interfaces/anatomical.py
  qsirecon/interfaces/scalar_mapping.py
  qsirecon/utils/bids.py
  qsirecon/workflows/recon/anatomical.py
Labels: bug

#152 Rename `--freesurfer-input` to `--fs-subjects-dir`
  .circleci/FreeSurferIngressTest.sh
  docs/builtin_workflows.rst
  docs/input_data.rst
  qsirecon/cli/parser.py
  qsirecon/config.py
  qsirecon/tests/test_cli.py
  qsirecon/workflows/recon/anatomical.py
Labels: bug, breaking-change

#156 Add page documenting output structure
  docs/index.rst
  docs/outputs.rst
Labels: documentation

#158 Add information about QSIPrep/QSIRecon releases
  docs/input_data.rst
Labels: documentation

#154 Pass DWI file metadata to reconstruction workflows
  qsirecon/workflows/base.py
  qsirecon/workflows/recon/amico.py
  qsirecon/workflows/recon/anatomical.py
  qsirecon/workflows/recon/build_workflow.py
  qsirecon/workflows/recon/converters.py
  qsirecon/workflows/recon/dipy.py
  qsirecon/workflows/recon/dsi_studio.py
  qsirecon/workflows/recon/mrtrix.py
  qsirecon/workflows/recon/pyafq.py
  qsirecon/workflows/recon/scalar_mapping.py
  qsirecon/workflows/recon/steinhardt.py
  qsirecon/workflows/recon/tortoise.py
  qsirecon/workflows/recon/utils.py
Labels: enhancement

#151 [ENH] Read session-specific anat data
  docs/installation.rst
  qsirecon/cli/parser.py
  qsirecon/cli/run.py
  qsirecon/cli/workflow.py
  qsirecon/config.py
  qsirecon/data/io_spec.json
  qsirecon/data/reports-spec-anat.yml
  qsirecon/data/reports-spec-dwi.yml
  qsirecon/data/reports-spec.yml
  qsirecon/interfaces/dsi_studio.py
  qsirecon/interfaces/freesurfer.py
  qsirecon/interfaces/utils.py
  qsirecon/reports/core.py
  qsirecon/tests/data/amico_noddi_outputs.txt
  qsirecon/tests/data/mrtrix_singleshell_ss3t_noact_outputs.txt
  qsirecon/tests/run_local_tests.py
  qsirecon/tests/test_cli.py
  qsirecon/tests/utils.py
  qsirecon/utils/bids.py
  qsirecon/workflows/base.py
  qsirecon/workflows/recon/anatomical.py
  qsirecon/workflows/recon/dipy.py
  qsirecon/workflows/recon/dsi_studio.py
  qsirecon/workflows/recon/tortoise.py
Labels: enhancement, breaking-change

#159 Remove underscore versions of all parameters
  qsirecon/cli/parser.py
Labels: breaking-change

#165 Fix extension in hsvs derivative
  qsirecon/workflows/recon/anatomical.py
Labels: bug

#167 [ENH] match to qsiprep nipype/nireports versions
  pyproject.toml
Labels: maintenance

#166 Make connectivity field names compatible with MATLAB
  docs/connectivity_matrices.rst
  qsirecon/interfaces/dsi_studio.py
  qsirecon/interfaces/mrtrix.py
Labels: bug, breaking-change

#172 Fix extension in ds_qsiprep_5tt_hsvs
  qsirecon/workflows/recon/anatomical.py
Labels: bug

#173 Add in Val's text for connectivity matrices
  docs/builtin_workflows.rst
  docs/connectivity_matrices.rst
  docs/index.rst
Labels: documentation

#175 Fix space in ds_qsiprep_5tt_hsvs
  docs/builtin_workflows.rst
  docs/nonscalars/dsistudio_autotrack.csv
  docs/nonscalars/dsistudio_gqi.csv
  docs/nonscalars/mrtrix_anat.csv
  docs/nonscalars/ss3t_autotrack.csv
  qsirecon/data/nonscalars/mrtrix_anat.yaml
  qsirecon/interfaces/mrtrix.py
  qsirecon/interfaces/scalar_mapping.py
  qsirecon/tests/data/mrtrix_multishell_msmt_hsvs_outputs.txt
  qsirecon/workflows/recon/anatomical.py
  qsirecon/workflows/recon/utils.py
Labels: bug

#177 Disable test_main in the CI integration tests
  .circleci/config.yml
  qsirecon/config.py
  qsirecon/tests/test_cli.py
  qsirecon/tests/utils.py
Labels: testing

#174 Make PlotPeaks robust enough that we don't need --writable-tempfs in singularity/apptainer
  qsirecon/cli/recon_plot.py
  qsirecon/interfaces/reports.py
  qsirecon/workflows/recon/amico.py
  qsirecon/workflows/recon/dipy.py
  qsirecon/workflows/recon/dsi_studio.py
  qsirecon/workflows/recon/mrtrix.py
Labels: bug

#178 Prepare for 1.0.0rc1 release
  .zenodo.json
  CITATION.cff
  docs/building_workflows.rst
  docs/builtin_workflows.rst
  docs/changes.md
  docs/comparisons.md
  docs/contributors.rst
  docs/help.rst
  docs/index.rst
  docs/input_data.rst
  docs/installation.rst
  docs/license.rst
  docs/quickstart.rst
Labels: maintenance, ignore-for-release
